export interface LibraryExercise {
  name: string
  sets: number
  reps: number
  rest: number
  timed: boolean // true = reps são segundos (mobilidade/alongamento)
}

export interface LibraryGroup {
  key: string
  label: string
  exercises: LibraryExercise[]
}

export const CARDIO_EXERCISE_NAMES: string[] = [
  'Corrida na esteira', 'Bicicleta ergométrica', 'Corda', 'Burpee', 'Polichinelo',
  'Step', 'Elíptico', 'Sprint', 'Jumping jack', 'Mountain climber',
  'Pular corda', 'Remo ergométrico', 'Escada rolante', 'Skipping', 'Box jump',
  'Battle rope', 'Kettlebell swing', 'Bear crawl', 'Assault bike', 'High knees',
  'Shadowboxing', 'Agility ladder', 'Corrida na rua', 'Stair climbing',
  'Rowing machine', 'Air bike', 'Ski erg',
]

export const EXERCISE_LIBRARY: LibraryGroup[] = [
  {
    key: 'cardio',
    label: 'Cardio',
    exercises: [
      { name: 'Corrida na esteira', sets: 1, reps: 20, rest: 0, timed: true },
      { name: 'Bicicleta ergométrica', sets: 1, reps: 20, rest: 0, timed: true },
      { name: 'Elíptico', sets: 1, reps: 20, rest: 0, timed: true },
      { name: 'Remo ergométrico', sets: 1, reps: 15, rest: 0, timed: true },
      { name: 'Assault bike', sets: 1, reps: 15, rest: 0, timed: true },
      { name: 'Escada rolante', sets: 1, reps: 15, rest: 0, timed: true },
      { name: 'Sprint', sets: 5, reps: 30, rest: 60, timed: true },
      { name: 'Corda', sets: 3, reps: 60, rest: 30, timed: true },
      { name: 'Pular corda', sets: 4, reps: 60, rest: 30, timed: true },
      { name: 'Battle rope', sets: 4, reps: 30, rest: 30, timed: true },
      { name: 'Burpee', sets: 3, reps: 15, rest: 30, timed: false },
      { name: 'Box jump', sets: 4, reps: 10, rest: 45, timed: false },
      { name: 'Polichinelo', sets: 3, reps: 40, rest: 20, timed: false },
      { name: 'Jumping jack', sets: 3, reps: 30, rest: 20, timed: false },
      { name: 'High knees', sets: 3, reps: 40, rest: 20, timed: false },
      { name: 'Skipping', sets: 3, reps: 30, rest: 20, timed: false },
      { name: 'Mountain climber', sets: 3, reps: 30, rest: 30, timed: true },
      { name: 'Bear crawl', sets: 3, reps: 20, rest: 30, timed: true },
      { name: 'Kettlebell swing', sets: 4, reps: 20, rest: 45, timed: false },
      { name: 'Shadowboxing', sets: 3, reps: 60, rest: 30, timed: true },
      { name: 'Step', sets: 3, reps: 30, rest: 20, timed: true },
      { name: 'Agility ladder', sets: 4, reps: 30, rest: 30, timed: true },
    ],
  },
  {
    key: 'peito',
    label: 'Peito',
    exercises: [
      { name: 'Supino reto com barra', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Supino inclinado com barra', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Supino declinado com barra', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Supino reto com halteres', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Supino inclinado com halteres', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Supino declinado com halteres', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Crucifixo reto com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Crucifixo inclinado com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Fly na máquina (peck deck)', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Crossover alto no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Crossover baixo no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Crossover neutro no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Flexão de braço', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Flexão inclinada', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Flexão declinada', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Flexão diamante', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Dips no paralelo (peito)', sets: 3, reps: 10, rest: 90, timed: false },
      { name: 'Supino fechado', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Pull-over com halter (peito)', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Svend press', sets: 3, reps: 15, rest: 60, timed: false },
    ],
  },
  {
    key: 'costas',
    label: 'Costas',
    exercises: [
      { name: 'Puxada frontal aberta', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Puxada supinada', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Puxada neutra (triângulo)', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Barra fixa (pull-up)', sets: 4, reps: 8, rest: 90, timed: false },
      { name: 'Chin-up', sets: 4, reps: 8, rest: 90, timed: false },
      { name: 'Remada curvada com barra', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Remada unilateral com halter', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Remada baixa no cabo', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Remada cavalinho', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Remada T-bar', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Remada inversa', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Levantamento terra', sets: 4, reps: 8, rest: 120, timed: false },
      { name: 'Levantamento terra romeno', sets: 3, reps: 10, rest: 90, timed: false },
      { name: 'Hiperextensão', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Superman', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Good morning', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Pullover com halter (costas)', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Pullover no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Remada face pull', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Serrote com halter', sets: 3, reps: 12, rest: 60, timed: false },
    ],
  },
  {
    key: 'gluteos',
    label: 'Glúteos',
    exercises: [
      { name: 'Hip thrust com barra', sets: 4, reps: 12, rest: 90, timed: false },
      { name: 'Hip thrust com halter', sets: 4, reps: 12, rest: 90, timed: false },
      { name: 'Hip thrust na máquina', sets: 4, reps: 15, rest: 90, timed: false },
      { name: 'Agachamento sumô', sets: 4, reps: 12, rest: 90, timed: false },
      { name: 'Agachamento goblet', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Elevação de quadril no chão', sets: 3, reps: 20, rest: 45, timed: false },
      { name: 'Elevação de quadril unilateral', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Passada com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Passada reversa', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Abdução de quadril na máquina', sets: 3, reps: 20, rest: 45, timed: false },
      { name: 'Abdução de quadril no cabo', sets: 3, reps: 20, rest: 45, timed: false },
      { name: 'Glúteo 4 apoios no cabo', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Stiff com barra (foco glúteo)', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Agachamento búlgaro', sets: 3, reps: 10, rest: 90, timed: false },
      { name: 'Step up no banco', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Monster walk com banda', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Clamshell com banda', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Agachamento lateral com banda', sets: 3, reps: 15, rest: 30, timed: false },
      { name: 'Leg press focado em glúteo', sets: 4, reps: 12, rest: 90, timed: false },
      { name: 'Bom dia com barra', sets: 3, reps: 12, rest: 90, timed: false },
    ],
  },
  {
    key: 'pernas',
    label: 'Pernas',
    exercises: [
      { name: 'Agachamento livre', sets: 4, reps: 10, rest: 120, timed: false },
      { name: 'Agachamento na máquina (Smith)', sets: 4, reps: 12, rest: 90, timed: false },
      { name: 'Agachamento hack com barra', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Hack squat na máquina', sets: 4, reps: 12, rest: 90, timed: false },
      { name: 'Leg press 45°', sets: 4, reps: 12, rest: 90, timed: false },
      { name: 'Leg press horizontal', sets: 4, reps: 12, rest: 90, timed: false },
      { name: 'Cadeira extensora', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Cadeira extensora unilateral', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Mesa flexora', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Cadeira flexora', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Cadeira flexora unilateral', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Stiff com halteres', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Stiff com barra', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Avanço com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Avanço com barra', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Avanço reverso', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Step up no banco', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Panturrilha em pé na máquina', sets: 4, reps: 20, rest: 45, timed: false },
      { name: 'Panturrilha sentado na máquina', sets: 4, reps: 20, rest: 45, timed: false },
      { name: 'Panturrilha no leg press', sets: 4, reps: 25, rest: 30, timed: false },
      { name: 'Cadeira adutora', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Cadeira abdutora', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Agachamento goblet', sets: 3, reps: 15, rest: 60, timed: false },
    ],
  },
  {
    key: 'ombros',
    label: 'Ombros',
    exercises: [
      { name: 'Desenvolvimento com barra', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Desenvolvimento com barra por trás', sets: 3, reps: 10, rest: 90, timed: false },
      { name: 'Desenvolvimento com halteres', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Desenvolvimento na máquina', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Arnold press', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Elevação lateral com halteres', sets: 4, reps: 15, rest: 60, timed: false },
      { name: 'Elevação lateral no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Elevação lateral na máquina', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Elevação frontal com halteres', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Elevação frontal com barra', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Elevação frontal no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Remada alta com barra', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Remada alta com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Face pull no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Shrug com barra', sets: 4, reps: 15, rest: 60, timed: false },
      { name: 'Shrug com halteres', sets: 4, reps: 15, rest: 60, timed: false },
      { name: 'Elevação lateral inclinado com halter', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Cuban press', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'W-press com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Push press', sets: 4, reps: 8, rest: 90, timed: false },
    ],
  },
  {
    key: 'biceps',
    label: 'Bíceps',
    exercises: [
      { name: 'Rosca direta com barra', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca direta com barra EZ', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca direta com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca alternada com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca martelo', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca martelo no cabo', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca concentrada', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Rosca Scott com barra', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca Scott com barra EZ', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca inclinada com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca no cabo (baixo)', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Rosca no cabo com corda', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Rosca inversa', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca Zottman', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca Spider', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Rosca 21', sets: 3, reps: 21, rest: 60, timed: false },
      { name: 'Rosca com banda elástica', sets: 3, reps: 15, rest: 45, timed: false },
    ],
  },
  {
    key: 'triceps',
    label: 'Tríceps',
    exercises: [
      { name: 'Tríceps testa com barra', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Tríceps testa com barra EZ', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Tríceps testa com halteres', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Tríceps francês com halter', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Tríceps francês com barra EZ', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Tríceps corda no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Extensão com barra reta no cabo', sets: 3, reps: 15, rest: 60, timed: false },
      { name: 'Extensão unilateral no cabo', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Extensão acima da cabeça no cabo', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Tríceps coice com halter', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Tríceps coice no cabo', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Mergulho no banco', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Dips no paralelo (tríceps)', sets: 4, reps: 10, rest: 90, timed: false },
      { name: 'Supino fechado', sets: 3, reps: 12, rest: 90, timed: false },
      { name: 'Kickback com halter', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Extensão unilateral com halter acima da cabeça', sets: 3, reps: 12, rest: 60, timed: false },
      { name: 'Push-down com barra V', sets: 3, reps: 15, rest: 60, timed: false },
    ],
  },
  {
    key: 'core',
    label: 'Core',
    exercises: [
      { name: 'Prancha frontal', sets: 3, reps: 30, rest: 30, timed: true },
      { name: 'Prancha lateral direita', sets: 3, reps: 20, rest: 30, timed: true },
      { name: 'Prancha lateral esquerda', sets: 3, reps: 20, rest: 30, timed: true },
      { name: 'Prancha com toque no ombro', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Prancha dinâmica (up-down)', sets: 3, reps: 10, rest: 45, timed: false },
      { name: 'Abdominal crunch', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Abdominal crunch inverso', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Abdominal bicicleta', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Abdominal oblíquo', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Abdominal no cabo', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Elevação de pernas', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Elevação de pernas no paralelo', sets: 3, reps: 15, rest: 45, timed: false },
      { name: 'Russian twist', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Russian twist com peso', sets: 3, reps: 20, rest: 30, timed: false },
      { name: 'Dead bug', sets: 3, reps: 10, rest: 30, timed: false },
      { name: 'Hollow body', sets: 3, reps: 30, rest: 30, timed: true },
      { name: 'V-sit', sets: 3, reps: 15, rest: 30, timed: false },
      { name: 'Ab rollout', sets: 3, reps: 10, rest: 60, timed: false },
      { name: 'Pallof press', sets: 3, reps: 12, rest: 45, timed: false },
      { name: 'Dragon flag', sets: 3, reps: 8, rest: 60, timed: false },
      { name: 'Windmill com kettlebell', sets: 3, reps: 8, rest: 45, timed: false },
      { name: 'Mountain climber', sets: 3, reps: 30, rest: 30, timed: true },
    ],
  },
  {
    key: 'mobilidade',
    label: 'Mobilidade',
    exercises: [
      { name: 'Mobilidade de quadril', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Abertura de quadril 90/90', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Mobilidade torácica', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Rotação torácica quadrupedia', sets: 2, reps: 10, rest: 15, timed: false },
      { name: 'Mobilidade glenoumeral', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Rotação de ombro com bastão', sets: 2, reps: 15, rest: 15, timed: false },
      { name: 'Mobilidade de tornozelo', sets: 2, reps: 15, rest: 15, timed: false },
      { name: 'Mobilidade de coluna em pé', sets: 2, reps: 10, rest: 15, timed: false },
      { name: 'Cat-cow', sets: 2, reps: 10, rest: 15, timed: false },
      { name: 'Bird dog', sets: 2, reps: 10, rest: 15, timed: false },
      { name: 'World greatest stretch', sets: 2, reps: 8, rest: 15, timed: false },
      { name: 'Hip hinge com bastão', sets: 2, reps: 10, rest: 15, timed: false },
      { name: 'Agachamento com pausa no fundo', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Flexão lateral de tronco', sets: 2, reps: 10, rest: 15, timed: false },
      { name: 'Ponte de glúteo (aquecimento)', sets: 2, reps: 15, rest: 15, timed: false },
      { name: 'Thread the needle', sets: 2, reps: 8, rest: 15, timed: false },
      { name: 'Crawling reverso', sets: 2, reps: 20, rest: 20, timed: true },
    ],
  },
  {
    key: 'alongamento',
    label: 'Alongamento',
    exercises: [
      { name: 'Alongamento de isquiotibiais em pé', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de isquiotibiais deitado', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de quadríceps em pé', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de panturrilha', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de flexor de quadril', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de adutores', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de glúteo deitado', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Pigeon pose', sets: 2, reps: 45, rest: 15, timed: true },
      { name: 'Alongamento de peito na parede', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de ombro cruzado', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de trapézio', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de pescoço lateral', sets: 2, reps: 20, rest: 15, timed: true },
      { name: 'Alongamento de lombar (joelhos ao peito)', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de dorsal (cat stretch)', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de bíceps', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Alongamento de tríceps', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Cobra (alongamento de abdome)', sets: 2, reps: 30, rest: 15, timed: true },
      { name: 'Criança (child pose)', sets: 2, reps: 45, rest: 15, timed: true },
      { name: 'Alongamento de tornozelo', sets: 2, reps: 20, rest: 15, timed: true },
    ],
  },
]
